org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

archives_base_name=cobblemon-indestructible-habitat
mod_id=cobblemon_indestructible_habitat
mod_version=1.x-DEV-SNAPSHOT
maven_group=dev.matthiesen
mod_name=Cobblemon Indestructible Habitat
mod_description=Simple Server-side mode to make Cobblemon's Habitat Blocks Indestructible
mod_license=MIT License
mod_license_url=https://github.com/Matthiesen-dev/cobblemon-indestructible-habitat/blob/main/LICENSE
mod_author=Adam Matthiesen
mod_author_id=adammatthiesen
mod_author_url=https://github.com/Adammatthiesen
github_url=https://github.com/Matthiesen-dev/cobblemon-indestructible-habitat
git_url=github.com/Matthiesen-dev/cobblemon-indestructible-habitat
modrinth_url=https://modrinth.com/mod/cobblemon-indestructible-habitat

# Used for prism deployment, not consumed by build-logic
minecraft_version=1.21.1